//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:46
// </auto-generated>
//--------------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using X.Entity;


namespace X.Dao
{

    /// <summary>
    /// EF 实体变更
    /// </summary>
    internal sealed class ReportingDbMigrationsConfiguration : DbMigrationsConfiguration<DataContext>
    {
        public ReportingDbMigrationsConfiguration()
        {
            AutomaticMigrationsEnabled = true;//任何Model Class的修改将会直接更新DB
            AutomaticMigrationDataLossAllowed = true;
        }
    }

    public class DataContext:DbContext
    {
        /// <summary>
        /// 数据库访问类"name=DataConnection"
        /// </summary>
        public DataContext() : base("name=DefaultConnection") {
		    //根据实体字段自动创建表，如果Entity有改到就更新到表结构
            Database.SetInitializer<DataContext>(new MigrateDatabaseToLatestVersion<DataContext, ReportingDbMigrationsConfiguration>());
		}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Types().Configure(entity => entity.ToTable("NN_" + entity.ClrType.Name));
            base.OnModelCreating(modelBuilder);
            base.Database.Log = new Action<string>(q => logger.Write("Debug", q));
            
        }
		 /// <summary>
		 /// Log
		 /// </summary>
		public virtual DbSet<Log> logs { get; set; }

		 /// <summary>
		 /// UserAccount
		 /// </summary>
		public virtual DbSet<UserAccount> useraccounts { get; set; }

    }
}
