//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:49
// </auto-generated>
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace X.Service
{
    public class Initializer
    {
        public static void AutoMapperInit()
        {
			AutoMapper.Mapper.CreateMap<Entity.Log, Models.Log>();
			AutoMapper.Mapper.CreateMap<Models.Log, Entity.Log>();

			AutoMapper.Mapper.CreateMap<Entity.UserAccount, Models.UserAccount>();
			AutoMapper.Mapper.CreateMap<Models.UserAccount, Entity.UserAccount>();

        }
    }
}
