//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:52
// </auto-generated>
//--------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace X.Models
{
    [Serializable]
    public class Log : BaseModel
    {
		public string Tenant { get; set; }
		public string Remark { get; set; }
    }
}
