//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:47
// </auto-generated>
//--------------------------------------------------------------------------------------
using System.Collections.Generic;
using X.Entity;

namespace X.IDao
{
    public interface IUserAccountDao : IBaseDao<UserAccount>, IDependency
    {
    }
}
