//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:44
// </auto-generated>
//--------------------------------------------------------------------------------------

using X.Entity;
using X.IDao;

namespace X.Dao
{   


    /// <summary>
    /// UserAccount
    /// </summary>
    public partial class UserAccountDao : BaseDao<UserAccount>, IUserAccountDao
	{
    }
}
