//--------------------------------------------------------------------------------------
// <auto-generated>
// QQ:584280962
// T4 生成时间2018/5/25 12:09:50
// </auto-generated>
//--------------------------------------------------------------------------------------
using System.Collections.Generic;
using X.IDao;

namespace X.IService
{
    public interface ILogService : IBaseService<Models.Log>, IDependency
    {
    }
}
